version: '3.3'
services:
  grafana:
    image: grafana/grafana:9.5.6
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: application_server
      POSTGRES_PASSWORD: redacted  
    restart: always
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:7.5
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: e@mail.com
      PGADMIN_DEFAULT_PASSWORD: redacted
    restart: always

  server:
    image: application_server:latest
    restart: always
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: application_server
      POSTGRES_PASSWORD: redacted
      PGPASSWORD: redacted
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres

volumes:
  pgadmin:
  postgres:
  grafana:
