{
 "title": "New dashboard",
 "time": { "from": "2024-07-27T22:13:21.296Z", "to": "2024-07-27T22:13:36.240Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nox, voc, \"time\" FROM storage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", AVG(temp) FROM storage GROUP BY \"time\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT pm1p0, pm2p5, pm4p0, pm10p0, \"time\" FROM storage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average PM2.5 Concentration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", AVG(pm2p5) FROM storage GROUP BY \"time\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperature and Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT temp, \"time\", hum FROM storage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average NOx Index",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(nox), \"time\" FROM storage GROUP BY \"time\" LIMIT 50 "
    }
   ]
  }
 ]
}